import { CTA, IconBadge, PageShell, SectionTitle, SiteHead } from '@/components/JoinHookV3';
const explorations=[['is-mobile','Interacción y usabilidad','Patrones, flujos y microcopias para experiencias claras.'],['is-dashboard','Paneles operativos','Jerarquías y componentes que apoyan seguimiento y decisión.'],['is-chart','Visualización de datos','Formas comprensibles y accionables de presentar información.'],['is-tourism','Experiencias para turismo y servicios','Información y acompañamiento digital conectado al contexto.'],['is-flow','Automatización con criterio','Automatizaciones útiles que reducen repetición sin perder control.'],['is-prototype','MVP y prototipos','Primeras versiones para validar antes de ampliar inversión.']];
export default function Lab(){return <PageShell><SiteHead title="JoinHook Lab | Prototipos, UX, datos y exploración de producto" description="JoinHook Lab reúne exploraciones de interfaz, automatización, datos, turismo, MVP y prototipos para aprender antes de escalar una solución." path="/lab"/>
<section className="jh3-hero jh3-simple-hero"><div className="jh3-hero-copy"><span className="jh3-kicker">JoinHook Lab</span><h1>Explorar, probar y refinar también es parte del trabajo.</h1><p>El Lab reúne ideas, pruebas de interfaz, conceptos de producto y líneas de exploración que ayudan a madurar soluciones antes de convertirlas en una herramienta o proyecto más grande.</p><div className="jh3-wave"/></div><div className="jh3-lab-notebook jh3-card" aria-hidden="true"><span>problema</span><span>flujo</span><span>usuario</span><span>prototipo</span></div></section>
<section className="jh3-section"><div className="jh3-lab-grid">{explorations.map(([visual,title,text],i)=><article className="jh3-card jh3-card-lift jh3-lab-card" key={title}><div className={`jh3-lab-visual ${visual}`}/><div className="jh3-lab-card-copy"><h3>{i+1}. {title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="jh3-section"><SectionTitle title="Cómo se usa el Lab"/><div className="jh3-grid-3">{[['search','Explorar','Detectar oportunidades y formular hipótesis desde problemas reales.'],['lightbulb','Aprender','Probar comportamientos, prioridades, lenguaje y viabilidad.'],['tool','Aplicar','Integrar lo que funciona en proyectos o herramientas concretas.']].map(([i,t,d])=><article className="jh3-card jh3-use-card" key={t}><IconBadge name={i as 'search'}/><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="jh3-section"><SectionTitle title="Lo que buscamos validar"/><div className="jh3-grid-5">{[['target','Necesidad real','¿El problema existe y vale la pena resolverlo?'],['people','Comprensión del usuario','¿Entendemos a las personas y su contexto?'],['tool','Viabilidad','¿Es técnica y operativamente sostenible?'],['eye','Claridad de uso','¿La solución se entiende sin esfuerzo excesivo?'],['chart','Valor práctico','¿Genera una mejora observable o medible?']].map(([i,t,d])=><article className="jh3-card jh3-sector-card" key={t}><IconBadge name={i as 'target'}/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="jh3-section"><SectionTitle title="Notas de exploración"/><div className="jh3-notes jh3-card">{['menos fricción','mejor flujo','datos más claros','más contexto','decisiones más simples'].map(x=><div className="jh3-note" key={x}>{x}</div>)}</div></section>
<CTA title="Algunas exploraciones se convierten en proyectos. Otras ayudan a mejorar los que ya existen." button="Ver proyectos" href="/proyectos"/></PageShell>}
