import { PageShell, SiteHead, SITE_EMAIL } from '@/components/JoinHookV3';

export default function PrivacyPage() {
    return <PageShell>
        <SiteHead title="Política de Privacidad | JoinHook" description="Cómo JoinHook trata los datos recibidos a través del sitio, formularios, newsletter y herramientas de medición." path="/privacidad" />
        <main className="jh-legal">
            <header className="jh-legal-header"><span className="jh3-kicker">Privacidad</span><h1>Política de Privacidad</h1><p>Última actualización: 1 de septiembre de 2026. Esta política explica qué información recibe JoinHook, para qué se utiliza y qué opciones tiene cada visitante.</p></header>
            <article>
                <section><h2>1. Responsable y alcance</h2><p>JoinHook, Chile, administra joinhook.cl y sus formularios públicos. Para consultas de privacidad puedes escribir a <a href={`mailto:${SITE_EMAIL}`}>{SITE_EMAIL}</a>.</p><p>Esta política cubre el sitio público, formularios de contacto, newsletter y medición del sitio. Productos que manejen información propia pueden contar con condiciones adicionales.</p></section>
                <section><h2>2. Datos que podemos recibir</h2><ul><li>Datos entregados voluntariamente en contacto: nombre, correo, teléfono opcional, empresa/proyecto, tipo y etapa de la necesidad y contenido del mensaje.</li><li>Correo y nombre opcional cuando una persona solicita suscribirse a la newsletter.</li><li>Datos técnicos limitados de seguridad y operación, como dirección IP temporal, user-agent, fecha y resultado de una solicitud.</li><li>Datos de navegación y atribución solo cuando corresponda al consentimiento otorgado: páginas, eventos, dispositivo, fuente, campaña y rendimiento.</li></ul><p>No solicitamos RUT, fecha de nacimiento, contraseñas, datos financieros ni categorías sensibles para el contacto comercial ordinario.</p></section>
                <section><h2>3. Finalidades</h2><ul><li>Responder consultas y evaluar proyectos o necesidades.</li><li>Gestionar oportunidades comerciales solicitadas por el visitante.</li><li>Enviar newsletter únicamente a quienes completen el flujo de doble confirmación.</li><li>Proteger el sitio contra abuso, bots y fraude.</li><li>Comprender rendimiento y uso del sitio cuando la persona autoriza analítica opcional.</li><li>Cumplir obligaciones legales o contractuales aplicables.</li></ul></section>
                <section><h2>4. Contacto y marketing son finalidades distintas</h2><p>Enviar una consulta a JoinHook no implica suscribirse a comunicaciones promocionales. La opción de newsletter es independiente, voluntaria y puede retirarse en cualquier momento mediante el enlace de baja de cada envío.</p></section>
                <section><h2>5. Proveedores</h2><p>Según la configuración habilitada, JoinHook puede utilizar servicios de infraestructura y seguridad, Cloudflare Turnstile, Brevo para suscripciones y correo, Google Analytics 4 y Google Search Console para medición, y Cloudflare Web Analytics para rendimiento. Cada integración se configura con minimización de datos y la analítica opcional queda sujeta a la elección de privacidad del visitante.</p></section>
                <section><h2>6. Analítica y datos personales</h2><p>No enviamos a herramientas de analítica el nombre, correo, teléfono, empresa ni contenido de los formularios. Los eventos comerciales se registran de manera agregada, por ejemplo: inicio de formulario, envío, clic en un CTA, producto consultado o clic de WhatsApp.</p></section>
                <section><h2>7. Conservación</h2><ul><li>Consultas comerciales: mientras exista una relación activa y, como política operativa general, hasta 24 meses desde la última interacción si no existe una obligación que requiera otro periodo.</li><li>Newsletter: mientras la suscripción continúe activa; después de una baja puede conservarse el mínimo registro necesario para respetar la exclusión.</li><li>Registros técnicos de seguridad: por periodos limitados y proporcionales al objetivo de protección.</li><li>Preferencias de consentimiento: hasta que se cambien, se eliminen del navegador o deban renovarse.</li></ul></section>
                <section><h2>8. Derechos y solicitudes</h2><p>Puedes solicitar información sobre tus datos, rectificación, eliminación cuando corresponda, oposición o retiro de consentimiento y otras facultades reconocidas por la normativa aplicable. Las solicitudes pueden dirigirse a <a href={`mailto:${SITE_EMAIL}`}>{SITE_EMAIL}</a>. Podremos solicitar antecedentes mínimos para verificar que la solicitud corresponde a la persona titular.</p></section>
                <section><h2>9. Seguridad</h2><p>Aplicamos controles como cifrado TLS, validación servidor, limitación de frecuencia, honeypot, protección anti-bot, encabezados de seguridad, restricciones de origen, minimización de datos y separación entre analítica y contenido de formularios. Ningún sistema conectado a Internet puede garantizar riesgo cero, por lo que estos controles se revisan y mejoran de manera continua.</p></section>
                <section><h2>10. Transferencias y servicios internacionales</h2><p>Algunos proveedores tecnológicos pueden procesar información fuera de Chile. JoinHook procura utilizar proveedores con medidas contractuales y técnicas adecuadas y limita los datos enviados a lo estrictamente necesario para la finalidad correspondiente.</p></section>
                <section><h2>11. Cookies y preferencias</h2><p>Las tecnologías no esenciales se controlan mediante el gestor de preferencias. Puedes aceptar, rechazar o configurar categorías y volver a abrir las preferencias desde el botón “Privacidad”. Consulta además la <a href="/cookies">Política de Cookies</a>.</p></section>
                <section><h2>12. Marco normativo</h2><p>JoinHook adapta sus prácticas a la normativa chilena vigente. La Ley 21.719, que moderniza la regulación de datos personales en Chile, entra en vigor el 1 de diciembre de 2026; esta política y los procesos asociados se han preparado considerando esa transición y serán revisados cuando corresponda.</p></section>
                <section><h2>13. Cambios</h2><p>La política puede actualizarse cuando cambien las funcionalidades, proveedores o requisitos aplicables. La fecha de actualización se mantendrá visible en esta página.</p></section>
            </article>
        </main>
    </PageShell>;
}
