import Link from 'next/link';
import { CTA, IconBadge, PageShell, ProjectPreview, SectionTitle, SiteHead } from '@/components/JoinHookV3';
import { projects } from '@/data-joinhook-v3';

export default function Projects() {
 return <PageShell>
  <SiteHead title="Proyectos y productos digitales | JoinHook" description="Conoce Control Gastronómico Express, JoinOps, SnowWise y Mi Gestión, proyectos de JoinHook en distintas etapas de exploración, desarrollo y validación." path="/proyectos" />
  <section className="jh3-hero jh3-simple-hero"><div className="jh3-hero-copy"><span className="jh3-kicker">Proyectos</span><h1>Productos y soluciones en construcción, validación y crecimiento.</h1><p>Cada proyecto responde a una necesidad concreta y evoluciona según su contexto, sus usuarios y su etapa de desarrollo.</p></div><div className="jh3-hero-object" aria-hidden="true"><span className="jh3-plant"/><span className="jh3-cup"/></div></section>
  <section className="jh3-section"><div className="jh3-project-grid">{projects.map(p => <article id={p.key === 'gestion' ? 'mi-gestion' : p.key} className="jh3-card jh3-card-lift jh3-project-card" key={p.key}><div className="jh3-project-preview"><ProjectPreview project={p.key}/></div><div className="jh3-project-card-content"><span className={`jh3-status ${p.tone==='green'?'':`is-${p.tone}`}`}>{p.status}</span><h2 className="jh3-project-title">{p.name}</h2><p>{p.description}</p><div className="jh3-project-card-tags">{p.tags.map(t=><span className="jh3-chip" key={t}>{t}</span>)}</div><Link className="jh3-card-link" href={p.href}>Ver detalle →</Link></div></article>)}</div></section>
  <section className="jh3-section"><SectionTitle title="Cómo leemos el estado de un proyecto"/><div className="jh3-grid-4">{[['search','gray','Exploración','Investigamos la necesidad, validamos supuestos y definimos el alcance inicial.'],['tool','blue','Prototipo activo','Existe una primera versión funcional para probar, aprender y ajustar.'],['code','amber','En desarrollo','El producto está en construcción activa e incorpora funciones clave.'],['check','green','Beta disponible','Existe una versión estable para uso real mientras continúa la mejora.']].map(([i,tone,t,d])=><article className="jh3-card jh3-feature-card" key={t}><IconBadge name={i as 'search'} tone={tone as 'gray'}/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="jh3-section"><SectionTitle title="Qué tienen en común"/><div className="jh3-grid-3">{[['people','Problema real','Nacen de necesidades concretas identificadas en trabajo y servicios reales.'],['tool','Uso práctico','Buscan simplificar tareas, ordenar información y facilitar adopción.'],['chart','Mejora continua','Evolucionan con retroalimentación, evidencia y tecnología apropiada.']].map(([i,t,d])=><article className="jh3-card jh3-use-card" key={t}><IconBadge name={i as 'people'}/><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <CTA title="¿Quieres seguir el desarrollo o probar una herramienta?" text="Revisa las herramientas disponibles o conversemos sobre un caso concreto." button="Ver herramientas" href="/herramientas"/>
 </PageShell>;
}
