import Link from 'next/link';
import { CTA, DashboardVisual, IconBadge, PageShell, SectionTitle, SiteHead } from '@/components/JoinHookV3';

export default function Tools() {
 return <PageShell>
  <SiteHead title="Herramientas digitales para operación y administración | JoinHook" description="Herramientas prácticas de JoinHook para inventario, compras, mermas, paneles operativos, administración y seguimiento de procesos." path="/herramientas" />
  <section className="jh3-hero"><div className="jh3-hero-copy"><span className="jh3-kicker">Herramientas</span><h1>Herramientas digitales prácticas para acompañar la operación.</h1><p>Reunimos soluciones diseñadas para organizar procesos, simplificar tareas y entregar información más útil al usuario o al administrador.</p><div className="jh3-wave"/></div><DashboardVisual variant="gastronomy"/></section>
  <section className="jh3-section"><div className="jh3-tool-feature jh3-card"><div><span className="jh3-status">BETA DISPONIBLE</span><h2>Control Gastronómico Express</h2><p>Pensado para pequeños negocios gastronómicos que necesitan registrar inventario, compras, mermas, proveedores, stock mínimo y respaldos sin partir por un sistema complejo.</p><div className="jh3-project-card-tags">{['Inventario','Compras','Mermas','Proveedores','Dashboard','PWA'].map(x=><span className="jh3-chip" key={x}>{x}</span>)}</div><div className="jh3-actions"><Link href="/herramientas/control-gastronomico-express" className="jh3-button jh3-button-primary">Conocer herramienta →</Link><Link href="/contacto" className="jh3-button jh3-button-secondary">Solicitar información →</Link></div></div><DashboardVisual variant="gastronomy"/></div></section>
  <section className="jh3-section"><SectionTitle title="Herramientas en evolución"/><div className="jh3-grid-3">{[['tool','amber','EN DESARROLLO','Módulos de JoinOps','Nuevos módulos para ampliar JoinOps según rubro y necesidad operativa.'],['chart','blue','EXPLORACIÓN','Paneles operativos','Dashboards personalizados para monitorear indicadores y estados relevantes.'],['document','violet','EN DISEÑO','Apoyos para administración','Herramientas simples para estandarizar tareas y mejorar seguimiento interno.']].map(([i,tone,status,title,text])=><article className="jh3-card jh3-feature-card" key={title}><IconBadge name={i as 'tool'} tone={tone as 'amber'}/><span className={`jh3-status is-${tone}`}>{status}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="jh3-section"><SectionTitle title="Qué buscamos en una herramienta"/><div className="jh3-grid-4">{[['eye','Claridad','Interfaces simples e información relevante para interpretar con rapidez.'],['check','Utilidad','Resolver tareas reales y reducir trabajo innecesario.'],['search','Trazabilidad','Registros confiables para seguir procesos, detectar desvíos y aprender.'],['chart','Escalabilidad','Crecer con nuevas necesidades sin perder simplicidad.']].map(([i,t,d])=><article className="jh3-card jh3-feature-card" key={t}><IconBadge name={i as 'eye'}/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="jh3-section"><SectionTitle title="Preguntas frecuentes"/><div className="jh3-faq"><details className="jh3-card" open><summary>¿Para quién están pensadas?</summary><p>Para negocios y equipos que necesitan herramientas prácticas para ordenar procesos, información y seguimiento.</p></details><details className="jh3-card"><summary>¿Cómo se implementan?</summary><p>De forma gradual, comenzando por el alcance que entrega valor sin introducir complejidad innecesaria.</p></details><details className="jh3-card"><summary>¿Pueden crecer con el negocio?</summary><p>El objetivo es que puedan evolucionar con nuevos procesos, usuarios e integraciones cuando el contexto lo justifique.</p></details></div></section>
  <CTA title="Si quieres probar una herramienta o evaluar una necesidad puntual, hablemos."/>
 </PageShell>;
}
